name: Docker Image CI

on:
  push:
    branches: 
      - "bufbuild"
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    #* Install buf
    - name: Install Buf.build
      uses: bufbuild/buf-setup-action@v1
      with:
        buf_user: ${{ secrets.BUFUSER }}
        buf_api_token: ${{ secrets.BUFTOKEN }}
      
    # - name: List
    #   run: |
    #     ls -al
    #     echo $PATH
    #     BUF_VERSION=$(curl -sSL https://api.github.com/repos/bufbuild/buf/releases/latest \
    #                | grep '"name":' \
    #                | head -1 \
    #                | cut -d : -f 2,3 \
    #                | tr -d '[:space:]\",')
    #     curl -sSL "https://github.com/bufbuild/buf/releases/download/${BUF_VERSION}/buf-$(uname -s)-$(uname -m)" \
    #     -o "/usr/local/bin/buf" && chmod +x "/usr/local/bin/buf"
    # - name: buf.build login
    #   shell: bash
    #   env: # Or as an environment variable
    #     BUF_TOKEN: ${{ secrets.BUFTOKEN }}
    #     BUF_USER: ${{ secrets.BUFUSER }}
    #   run: |
    #     echo $BUF_USER
    #     echo "$BUF_USER"
    #     buf registry login --verbose --username "$BUF_USER" --token-stdin "$BUF_TOKEN"
    - name: Build Docker image
    # - uses: actions/checkout@v3
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build . --platform linux/amd64 -t buf.build/jasonkolodziej/redact:v0.1.1
    #* Push module to the BSR
    # - uses: bufbuild/buf-push-action@v1
    #   with:
    #     buf_token: ${{ secrets.BUFTOKEN }}
    #     # https://buf.build/docs/ci-cd/github-actions#buf-push
    #     input: --image buf.build/jasonkolodziej/redact:v0.1.1
    #     create_visibility: private
    #     draft: ${{ github.ref_name != 'main'}}
    
    - name: buf.build Push Plugin
      uses: bufbuild/buf-setup-action@v1
      with:
        buf_user: ${{ secrets.BUFUSER }}
        buf_api_token: ${{ secrets.BUFTOKEN }}
    - run: | 
        buf registry login
        buf registry plugin push --visibility private --image buf.build/jasonkolodziej/redact:v0.1.1
    - name: buf.build logout
      run: buf registry logout
    

          
