name: Docker Image CI

on:
  push:
    branches: 
      - "bufbuild"
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: List
      run: |
        ls -al
        echo $PATH
        BUF_VERSION=$(curl -sSL https://api.github.com/repos/bufbuild/buf/releases/latest \
                   | grep '"name":' \
                   | head -1 \
                   | cut -d : -f 2,3 \
                   | tr -d '[:space:]\",')
        curl -sSL "https://github.com/bufbuild/buf/releases/download/${BUF_VERSION}/buf-$(uname -s)-$(uname -m)" \
        -o "/usr/local/bin/buf" && chmod +x "/usr/local/bin/buf"
    - name: buf.build login
      env: # Or as an environment variable
        BUF_TOKEN: ${{ secrets.BUFTOKEN }}
        BUF_USER: ${{ secrets.BUFUSER }}
      run: |
        buf registry login --username ${{ env.BUF_USER }}
    - name: Build the Docker image
    # - uses: actions/checkout@v3
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build . --platform linux/amd64 -t buf.build/jasonkolodziej/redact:v0.1.1
    - name: buf.build logout
      env: # Or as an environment variable
        BUF_USER: ${{ secrets.BufUser }}
      run: |
        buf registry logout
    - name: buf.build uninstall
      run: |
        buf
        BIN="/usr/local/bin" && \
        rm -f "${BIN}/buf"
    

          
