name: Docker Image CI

on:
  push:
    branches: 
      - "bufbuild"
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: List
    - uses: actions/checkout@v3
      run: |
        ls -al
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build --platform linux/amd64 -t buf.build/jasonkolodziej/redact:v0.1.1 Dockerfile.redact
